# Generated by Django 5.0 on 2024-01-02 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema_Hall',
            fields=[
                ('hall_number', models.IntegerField(primary_key=True, serialize=False)),
                ('hall_row', models.IntegerField(default=0)),
                ('hall_col', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Halls_Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_number_row', models.IntegerField(default=1)),
                ('sit_number_col', models.IntegerField(default=1)),
                ('is_taken', models.BooleanField(default=False)),
                ('hall_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seans.cinema_hall')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
                ('hall_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seans.cinema_hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seans.halls_seats')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seans.showing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
